// flow-typed signature: a69bb5c89ddfdce9aac1e060346038e0
// flow-typed version: <<STUB>>/fs-extra^x.x.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-extra' {
  declare module.exports: any;
}