import React from 'react';
import {
  BlockHeading,
  BlockHeadingWireframe,
  BlockParagraph,
  BlockParagraphWireframe,
  BlockImage,
  BlockImageWireframe,
  BlockImageParagraph,
  BlockImageParagraphWireframe,
  BlockCard,
  BlockCardWireframe,
  BlockQuote,
  BlockQuoteWireframe,
  BlockVideo,
  BlockVideoWireframe,
  BlockCarousel,
  BlockCarouselWireframe,
  GenericPreview,
  BlockColorSwatch,
  BlockColorSwatchForm,
  BlockColorSwatchWireframe,
  BlockBox,
  BlockBoxForm,
  BlockBoxWireframe,
} from './index';

export default {
  BlockBox: {
    element: <BlockBox />,
    preview: <GenericPreview />,
    form: <BlockBoxForm />,
    name: 'Box',
    wireframe: <BlockBoxWireframe />,
  },
  BlockParagraph: {
    element: <BlockParagraph />,
    preview: <GenericPreview />,
    name: 'Paragraph',
    wireframe: <BlockParagraphWireframe />,
  },
  BlockHeading: {
    element: <BlockHeading />,
    preview: <GenericPreview />,
    name: 'Heading',
    wireframe: <BlockHeadingWireframe />,
  },
  BlockImage: {
    element: <BlockImage />,
    preview: <GenericPreview />,
    name: 'Image',
    wireframe: <BlockImageWireframe />,
  },
  BlockImageParagraph: {
    element: <BlockImageParagraph />,
    preview: <GenericPreview />,
    name: 'Image + Paragraph',
    wireframe: <BlockImageParagraphWireframe />,
  },
  BlockCardParagraph: {
    element: <BlockCard />,
    preview: <GenericPreview />,
    name: 'Card + Paragraph',
    wireframe: <BlockCardWireframe />,
  },
  BlockQuote: {
    element: <BlockQuote />,
    preview: <GenericPreview />,
    name: 'Quote',
    wireframe: <BlockQuoteWireframe />,
  },
  BlockVideo: {
    element: <BlockVideo />,
    preview: <GenericPreview />,
    name: 'Video',
    wireframe: <BlockVideoWireframe />,
  },
  BlockCarousel: {
    element: <BlockCarousel />,
    preview: <GenericPreview />,
    name: 'Carousel',
    wireframe: <BlockCarouselWireframe />,
  },
  BlockColorSwatch: {
    element: <BlockColorSwatch />,
    name: 'Color Swatch',
    preview: <GenericPreview />,
    form: <BlockColorSwatchForm />,
    wireframe: <BlockColorSwatchWireframe />,
  },
};
