import React from 'react';
import {
  BlockHeading,
  BlockHeadingWireframe,
  BlockParagraph,
  BlockParagraphWireframe,
  BlockParagraphForm,
  BlockImage,
  BlockImageForm,
  BlockImageWireframe,
  BlockCard,
  BlockCardForm,
  BlockCardWireframe,
  BlockQuote,
  BlockQuoteForm,
  BlockQuoteCardForm,
  BlockQuoteWireframe,
  BlockVideo,
  BlockVideoWireframe,
  BlockVideoForm,
  BlockAssetLink,
  BlockAssetLinkForm,
  BlockAssetLinkWireframe,
  BlockCarousel,
  BlockCarouselForm,
  BlockCarouselWireframe,
  GenericPreview,
  BlockColorSwatch,
  BlockColorSwatchForm,
  BlockColorSwatchPreview,
  BlockColorSwatchWireframe,
  BlockBox,
  BlockBoxForm,
  BlockHeadingForm,
  BlockBoxWireframe,
  BlockHero,
  BlockHeroForm,
  BlockHeroWireframe,
  BlockImageGallery,
  BlockImageGalleryWireframe,
  BlockButton,
  BlockButtonForm,
  BlockButtonWireframe,
  BlockCarouselWithContent,
  BlockCarouselWithContentForm,
  BlockCarouselWithContentWireframe,
} from './index';

export default {
  BlockBox: {
    element: <BlockBox />,
    preview: <GenericPreview />,
    form: <BlockBoxForm />,
    name: 'Box',
    wireframe: <BlockBoxWireframe />,
  },
  BlockParagraph: {
    element: <BlockParagraph />,
    preview: <GenericPreview />,
    form: <BlockParagraphForm />,
    name: 'Paragraph',
    wireframe: <BlockParagraphWireframe />,
  },
  BlockHeading: {
    element: <BlockHeading />,
    preview: <GenericPreview />,
    form: <BlockHeadingForm />,
    name: 'Headline',
    wireframe: <BlockHeadingWireframe />,
  },
  BlockImage: {
    element: <BlockImage />,
    preview: <GenericPreview />,
    form: <BlockImageForm />,
    name: 'Image',
    wireframe: <BlockImageWireframe />,
  },
  BlockImageGallery: {
    element: <BlockImageGallery />,
    preview: <GenericPreview />,
    form: <BlockCarouselForm />,
    name: 'Image Gallery',
    wireframe: <BlockImageGalleryWireframe />,
  },
  BlockHero: {
    element: <BlockHero />,
    preview: <GenericPreview />,
    form: <BlockHeroForm />,
    name: 'Hero',
    wireframe: <BlockHeroWireframe />,
  },
  BlockCarousel: {
    element: <BlockCarousel />,
    preview: <GenericPreview />,
    form: <BlockCarouselForm />,
    name: 'Carousel',
    wireframe: <BlockCarouselWireframe />,
  },
  BlockCarouselWithContent: {
    element: <BlockCarouselWithContent />,
    preview: <GenericPreview />,
    form: <BlockCarouselWithContentForm />,
    name: 'Carousel With Content',
    wireframe: <BlockCarouselWithContentWireframe />,
  },
  BlockVideo: {
    element: <BlockVideo />,
    preview: <GenericPreview />,
    form: <BlockVideoForm />,
    name: 'Video',
    wireframe: <BlockVideoWireframe />,
  },
  BlockCardParagraph: {
    element: <BlockCard />,
    preview: <GenericPreview />,
    form: <BlockCardForm />,
    name: 'Card',
    wireframe: <BlockCardWireframe />,
  },
  BlockQuote: {
    element: <BlockQuote />,
    preview: <GenericPreview />,
    form: <BlockQuoteForm />,
    name: 'Quote',
    wireframe: <BlockQuoteWireframe />,
  },
  BlockQuoteCard: {
    element: <BlockQuote />,
    preview: <GenericPreview />,
    form: <BlockQuoteCardForm />,
    name: 'Quote w/ Card',
    wireframe: <BlockQuoteWireframe />,
  },
  BlockColorSwatch: {
    element: <BlockColorSwatch />,
    name: 'Color Swatch',
    preview: <BlockColorSwatchPreview />,
    form: <BlockColorSwatchForm />,
    wireframe: <BlockColorSwatchWireframe />,
  },
  BlockAssetLink: {
    element: <BlockAssetLink />,
    name: 'Asset Link (Deprecated, use Block Button)',
    preview: <GenericPreview />,
    form: <BlockAssetLinkForm />,
    wireframe: <BlockAssetLinkWireframe />,
  },
  BlockButton: {
    element: <BlockButton />,
    name: 'Button',
    preview: <GenericPreview />,
    form: <BlockButtonForm />,
    wireframe: <BlockButtonWireframe />,
  },
};
