export default {
  asiaPacific: [
    { label: 'Australia', value: 'Australia' },
    { label: 'China', value: 'https://www.hpe.hpstore-china.com' },
    { label: 'Hong Kong', value: 'Hong-Kong' },
    { label: 'India', value: 'India' },
    { label: 'Indonesia', value: 'Indonesia' },
    { label: 'Japan', value: 'Japan' },
    { label: 'Malaysia', value: 'Malaysia' },
    { label: 'New Zealand', value: 'New-Zealand' },
    { label: 'Philippines', value: 'Philippines' },
    { label: 'Singapore', value: 'Singapore' },
    { label: 'South Korea', value: 'South-Korea' },
    { label: 'Taiwan', value: 'Taiwan' },
    { label: 'Vietnam', value: 'Vietnam' },
  ],
  emea: [
    { label: 'Algeria', value: 'emea' },
    { label: 'Austria | German', value: 'emeade' },
    { label: 'Azerbaijan', value: 'emea' },
    { label: 'Belarus', value: 'emea' },
    { label: 'Belgium', value: 'emea' },
    { label: 'Bulgaria', value: 'emea' },
    { label: 'Croatia', value: 'emea' },
    { label: 'Cyprus', value: 'emea' },
    { label: 'Czech Republic', value: 'emea' },
    { label: 'Denmark', value: 'emea' },
    { label: 'Egypt', value: 'emea' },
    { label: 'EMEA', value: 'emea' },
    { label: 'Finland', value: 'emea' },
    { label: 'France | French', value: 'emeafr' },
    { label: 'Georgia', value: 'emea' },
    { label: 'Germany | German', value: 'emeade' },
    { label: 'Greece', value: 'emea' },
    { label: 'Hungary', value: 'emea' },
    { label: 'Iceland', value: 'emea' },
    { label: 'Israel', value: 'emea' },
    { label: 'Italy | Italian', value: 'emeait' },
    { label: 'Luxemborg', value: 'emea' },
    { label: 'Macedonia', value: 'emea' },
    { label: 'Malta', value: 'emea' },
    { label: 'Montenegro', value: 'emea' },
    { label: 'Morocco', value: 'emea' },
    { label: 'Netherlands', value: 'emea' },
    { label: 'Nigeria', value: 'emea' },
    { label: 'Norway', value: 'emea' },
    { label: 'Poland', value: 'emea' },
    { label: 'Portugal', value: 'emea' },
    { label: 'Romania', value: 'emea' },
    { label: 'Russia', value: 'emea' },
    { label: 'Saudi Arabia', value: 'emea' },
    { label: 'Serbia', value: 'emea' },
    { label: 'Slovakia', value: 'emea' },
    { label: 'South Africa', value: 'South-Africa' },
    { label: 'Spain | Spanish', value: 'emeasp' },
    { label: 'Sweden', value: 'emea' },
    { label: 'Switzerland', value: 'emea' },
    { label: 'Turkey', value: 'emea' },
    { label: 'Ukraine', value: 'emea' },
    { label: 'United Arab Emirates', value: 'United-Arab-Emirates' },
    { label: 'United Kingdom', value: 'emea' },
  ],
  northAmerica: [
    { label: 'Canada', value: 'canada' },
    { label: 'Mexico', value: 'Mexico' },
    { label: 'Puerto Rico', value: 'usa' },
    { label: 'United States', value: 'usa' },
  ],
  southAmerica: [
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Bolivia', value: 'Bolivia' },
    { label: 'Brazil', value: 'Brazil' },
    { label: 'Chile', value: 'Chile' },
    { label: 'Colombia', value: 'Colombia' },
    { label: 'Costa Rica', value: 'Costa-Rica' },
    { label: 'Ecuador', value: 'Ecuador' },
    { label: 'Paraguay', value: 'Paraguay' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Uruguay', value: 'Uruguay' },
    { label: 'Venezuela', value: 'Venezuela' },
  ],
};
